### ISSUE TITLE
Support for metavariables in interpolated strings for Scala

### ISSUE THREAD

**Issue by sampion88** [opengrep/opengrep#106]
**Is your feature request related to a problem? Please describe.**
When looking for patterns in interpolated strings like 
```yaml
- pattern: s"..."
```
it is possible to determine if your tainted user input goes into the interpolated string.
But what is not possible is something like this:
```yaml
- focus-metavariable: $TAINTED
- pattern: s"$BAD...$TAINTED"
- metavariable-regex:
      metavariable: $BAD
      regex: This text cannot be followed by a tainted value
```

**Describe the solution you'd like**
It should be possible to add metavariables into interpolated strings like s"..." and f"..." for Scala.
I think a second issue arises if you also want to add taint analysis. Variables are also identified with a $ eg:
```scala
val name = "James"
val age = 30
println(s"$name is $age years old") 
```

**Describe alternatives you've considered**

**Use case**
What will this feature enable for you?

**Additional context**
