### ISSUE TITLE
JSP files support via extract mode

### ISSUE THREAD

**Issue by Kirill89** [opengrep/opengrep#110]
**Is your feature request related to a problem? Please describe.**
The original problem is described [here](https://github.com/semgrep/semgrep/issues/7276). I have a requirement of analyzing Java code inside `.jsp` files with the same rules as I use in Java.

**Describe the solution you'd like**
In Semgrep, I've tried to use a very interesting experiment called "Extract mode". It never worked properly (see [the original issue](https://github.com/semgrep/semgrep/issues/7276#issuecomment-1457026766) in the Semgrep repo) and it was deprecated and removed in Semgrep 1.65.0 ([ref](https://semgrep.dev/docs/writing-rules/experiments/deprecated-experiments)).

I believe proper implementation of Extract mode can be a good thing for Opengrep (and a good solution for my use case).

**Use case**
Improve rules coverage of Web Java projects.

**Comment by Iurii-Slobodchikov** [comment]
I also used extract mode for the JS checks inside HTML files using this rule:
```
- id: extract-js-from-html
    mode: extract
    pattern: |
        <script>$...BODY</script>
    extract: $...BODY
    languages:
      - html
    dest-language: javascript
```
And it worked like a charm until Semgrep removed it in this release:
https://github.com/semgrep/semgrep/releases/tag/v1.65.0
