### ISSUE TITLE
Escaped backticks inside format string in Javascript prevent taint to be be found

### ISSUE THREAD

**Issue by sampion88** [opengrep/opengrep#112]
**Describe the bug**
rule def:
```yaml
rules:
  - id: rule_id
    message: message
    languages:
      - javascript
    severity: ERROR
    mode: taint
    pattern-sinks:
              - patterns:
                  - pattern: |
                     `$FIRST${$EXPR}...`
                  - metavariable-regex:
                      metavariable: $FIRST
                      regex: ^This text should not go before tainted variable,\s.*
    pattern-sources:
              - patterns:
                  - pattern-inside: |
                      (..., $INPUT, ...) => {
                        ...
                      }
                  - pattern: $INPUT
```
code:
```javascript
resolve: (taint) => {
        return ` This text should not go before tainted variable, \`Between backticks\` 
           ${taint}`
      }
```
\`Between backticks\` prevents 'taint' to be found.
If the escaped backtick are removed, the rule works as expected.
no error messages are being generated
**To Reproduce**
Steps to reproduce the behavior.
If the issue is dependent on a specific rule and/or files, please paste the command line parameters and applicable file contents.
**Expected behavior**
Escaped backtick inside format string should be ignored
**Screenshots**
**What is the priority of the bug to you?**
- [ ] P0: blocking your adoption of Opengrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed
**Environment**
Are you running off docker, an official binary, a local build?
**Use case**
What will fixing this bug enable for you?
