### ISSUE TITLE
Add flag to return all taints

### ISSUE THREAD

**Issue by fryckbos** [opengrep/opengrep#176]
**Is your feature request related to a problem? Please describe.**
Opengrep currently returns a single taint, I would like to get all taints instead.

**Describe the solution you'd like**
Add a flag that allows to return all taints.

**Describe alternatives you've considered**
None

**Use case**
In order to fix the detected vulnerabilities, I want to know all taints so they can all be fixed at once.

**Additional context**
Code sample

```
import express from "express";
import { MongoClient } from "mongodb";

const app = express();
app.use(express.json());
const PORT = 3000;

const client = new MongoClient(process.env.MONGO_URI);

app.post("/login", function (req, res) {
  const database = client.db("database");
  const Users = database.collection("users");
  const user = Users.findOne({
    name: req.body.name,
    password: req.body.password,
  });

  if (user) {
    res.send(`Welcome ${user}`);
  } else {
    res.send("User not found");
  }
});

app.listen(PORT, function (err) {
  if (err) console.log(err);
  console.log("Server listening on PORT", PORT);
});
```

Rule
```
  pattern-sinks:
    - patterns:
        - pattern: $DB. ... .$METHOD($INPUT,...)
        - metavariable-regex:
            metavariable: $METHOD
            regex: ^findOne$
        - focus-metavariable: $INPUT
  pattern-sources:
    - patterns:
        - pattern-either:
            - patterns:
                - pattern-inside: function ... ($REQ, $RES) {...}
                - pattern-either:
                    - pattern: $REQ.$QUERY
                    - pattern: $REQ.$BODY.$PARAM
```

I want to get both `req.body.name` and `req.body.password` as taints.
