### ISSUE TITLE
Better support for String Templates in Kotlin

### ISSUE THREAD

**Issue by sampion88** [opengrep/opengrep#189]
**Is your feature request related to a problem? Please describe.**
When looking for patterns with tainted user input in template strings like
```kotlin
fun foo(taintedString: String): String {
     return bar("This is bad ${taintedString}")
}
fun foo(taintedString: String): String {
     return bar("This is bad $taintedString")
}
fun foo(taintedString: String): String {
     return bar("""This is bad 
            $taintedString""")
}
```
It is possible to determine if your tainted user input goes into the template string.
But what is not possible, is something like this:
```yaml
- focus-metavariable: $TAINTED
- pattern-either:
  - pattern: "$BAD$TAINTED"
  - pattern: "$BAD${$TAINTED}"
- metavariable-regex:
      metavariable: $BAD
      regex: This is bad
```

**Describe the solution you'd like**
Make it possible to check for text inside a template string using metavariable-regex, also finding the tainted parameter (like it already does).

**Describe alternatives you've considered**
There is a workaround, but it is far from perfect and a bit buggy.
```yaml
- focus-metavariable: $TAINTED
- pattern-either:
    - pattern: |
        "...${$TAINTED}..."
    - pattern: |
        """...${$TAINTED}..."""
    - pattern-regex: |
        ^.*"("")?This is bad.*
```
I have to add the beginning of the string in the pattern-regex. But I cannot add the ending, or it does not work anymore, which makes it unfit for the multi line strings.
