### ISSUE TITLE
Stabilize language support for Dart

### ISSUE THREAD

**Issue by willem-delbare** [opengrep/opengrep#212]

**Comment by sampion88** [comment]
Simple taint example not working

```yaml
rules:
  - id: AIK_dart_sqflite-injection
    message: SQL injection in Sqflite database
    languages:
      - dart
    severity: ERROR
    mode: taint
    pattern-sources:
      - patterns:
        - pattern-inside: $FUNC(..., $TYPE $PARAM, ...) {...}
        - focus-metavariable: $PARAM
    pattern-sinks:
      - patterns:
        - pattern: $DB.execute(..., $PARAM, ...)
        - focus-metavariable: $PARAM
```
```dart
import 'package:sqflite/sqflite.dart';

class _WebViewExampleState {

  String writeToDB(String name, String other) {
    final database = openDatabase(
      join(await getDatabasesPath(), 'doggie_database.db'),
      onCreate: (db, version) {
        // ruleid: AIK_dart_sqflite-injection
        return db.execute(
          'CREATE TABLE ' + name + '(id INTEGER PRIMARY KEY, name TEXT, age INTEGER)',
        );
      },
      version: 1,
    );
  }

  String writeToDB(String name, String other) {
        // ruleid: AIK_dart_sqflite-injection
        return db.execute(
          'CREATE TABLE ' + name + '(id INTEGER PRIMARY KEY, name TEXT, age INTEGER)',
        );
  }

  String writeToDB(String name, String other) {
        // ok: AIK_dart_sqflite-injection
        return db.execute(
          'CREATE TABLE dog(id INTEGER PRIMARY KEY, name TEXT, age INTEGER)',
        );
  }
}
```
This gives zero results.
When running in opengrep-playground, I get the impression it finds some patterns, but the line numbers are incorrect. 
On the image below, my mouse is on the sink pattern and some random line is highlighting in the code. Cannot reproduce in cli though.
![Image](https://github.com/user-attachments/assets/91e01b63-7867-45f8-89c8-efb395140e4d)
