### ISSUE TITLE
In Java metavariable did not capture part of a function parameter if a parameter starts with "("

### ISSUE THREAD

**Issue by Kirill89** [opengrep/opengrep#23]
This is a copy of my original ticket opened to the Semgrep project: https://github.com/semgrep/semgrep/issues/7957
This one was quite annoying for a while. I tried to fix it myself but didn't manage to find time. Instead I have a few hacks in my Python code to overcome this. But it would be nice to fix it here.

I'm going to slowly migrate the rest of my issues opened to Semgrep here, as I'm planning to move from Semgrep to Opengrep asap.

**Describe the bug**

Metavariable did not capture part of a function parameter.

Java code:

```
public class A {
  public void a(HttpServletRequest b) {
      var catPicture = 
          new File(catPicturesDirectory, (id == null ? RandomUtils.nextInt(1, 11) : id) + ".jpg");
  }
}
```

Rule:

```
rules:
  - id: test
    patterns:
    - pattern: new $TYPE($ARG_PARENT, $ARG_CHILD);
    - metavariable-regex:
        metavariable: $TYPE
        regex: (File)
    message: "parent: $ARG_PARENT, child: $ARG_CHILD"
    severity: WARNING
    languages:
      - java
```

Expected message: `parent: catPicturesDirectory, child: (id == null ? RandomUtils.nextInt(1, 11) : id) + ".jpg"`
Actual message: `parent: catPicturesDirectory, child: id == null ? RandomUtils.nextInt(1, 11) : id) + ".jpg"`

**To Reproduce**

`./_build/install/default/bin/semgrep scan -f /path/to/rule.yml /path/to/proj/with/java --json`

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Opengrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**

Local build on Mac from main branch.

**Use case**

I use Semgrep JSON output as part of my program analysis tool. Correct metavariables positions are important for me.
