### ISSUE TITLE
PHP 5->Php 8.4 parser

### ISSUE THREAD

**Issue by corneliuhoffman** [opengrep/opengrep#297]
## **Describe the bug**

 In issue #295 we discovered 2 things
1. the menhir parser (default) is not updated to latest php
2. there is a bug in the tree-sitter parser that interpolates strings wrongly. 

While we should eventually fix the interpolation issue in tree-sitter this does not help since the pattern parsing in php is done via menhir.
In digging in the php updates I found other unparsable syntax:

issues remainig for the parser:
1. [ ] static return type:

```php
function f(): static {}
```
2. [x]  Match expressions:
```php
match($x) {
    1 => 'one',
    2 => 'two',
};
```
3. [x]  Enums:
```php
enum Status {
  case Active;
  case Inactive;
}
```
4. [x]  Null coallescing assignment
```php
$a ??= 'default';
```
5. [x]  Array spread:
```php
$parts = ['apple', 'pear'];
$fruits = ['banana', 'orange', ...$parts, 'watermelon'];
```
and non-numeric
```php
$arr = ["a" => 1, ...$b];
```
6. [ ]  Readonly props or classes
```php
readonly class C { public int $i; }
class C { public readonly int $i; }
```
7. [ ]  Dnf types, standalone types
```php
function f((A&B)|C $x) {}
```
8. [ ]  propery hooks
```php
public string $credits { get { /*...*/ } }
```
9. [ ]  Asymmetric visibility
```php
public private(set) int $i;
```
10. [x]  new without parentheses chaining
```php
new C($a)->meth();
```
11. [ ] [Class constant visibility](https://wiki.php.net/rfc/class_const_visibility), introduced in PHP version 7.1. (thanks @bblumenwiese)

Example:
```php
class C { public const string P = 'Public'; }
class C { protected const string P = 'Protected'; }
class C { private const string P = 'Private'; }
```

### **To Reproduce**
Steps to reproduce the behavior.

This bug is somewhat subtle and so not very obvious to reproduce, there are two possible ways
1. in Parse_target2.ml comment out [this line](https://github.com/opengrep/opengrep/blob/80a6332c484b9e66bfc00d172c986da84f0523fb/src/parsing_languages/Parse_target2.ml#L129), make the project and try to parse any of the above.
2. do not comment the project but create code containing one of the above as well as the following syntax:
```php
function f($filename) {
    "convert $filename";
}
```
then apply the following rule 
```yaml
rules:
- id: embedded_word
  message: "The web server executes a command on potential unescaped user input, which may lead to remote command execution."
  languages:
    - php
  severity: ERROR
  mode: taint
  options:
    taint_assume_safe_numbers: true
  pattern-sinks:
  - patterns:  
    - pattern: $SOURCE
  pattern-sources:
  - patterns:
    - focus-metavariable: $SOURCE
    - pattern-either:
        - pattern: function $FUNC(..., $SOURCE, ...) { ... }
```
If opengrep finds the rule then you are ok. Otherwise you messed up.

### **Expected behavior**
Menhir should parse all the above syntax
