### ISSUE TITLE
Kotlin: Taint analysis does not propagate through the Elvis operator (`?:`)

### ISSUE THREAD

**Issue by fxbru** [opengrep/opengrep#312]
### Description

Hello Opengrep Team,

I've identified a limitation in the taint analysis engine for the Kotlin language. When a variable is assigned a value from a taint source using the Elvis operator (`?:`), the taint is not propagated correctly. This can lead to false negatives for rules relying on taint mode.

### Steps to Reproduce

1.  **Rule:** A basic taint-tracking rule to find format string injections.
    ```yaml
    rules:
    - id: format-string-injection
      mode: taint
      pattern-sources:
        - pattern: $INTENT.getStringExtra(...)
      pattern-sinks:
        - pattern: String.format($FORMAT, ...)
      message: Format String Injection
      languages: [kotlin]
      severity: ERROR
    ```

2.  **Kotlin Code:** A file containing two functions. The first uses the Elvis operator, and the second uses a direct assignment.
    ```kotlin
    // test.kt
    import android.content.Intent

    class MyActivity {
        // Taint flow is NOT detected in this function
        fun processIntentData1(intent: Intent) {
            val formatString = intent.getStringExtra("format_string") ?: return
            // The 'formatString' variable should be considered tainted here.
            String.format(formatString, "argument")
        }

        // Taint flow IS detected correctly in this function
        fun processIntentData2(intent: Intent) {
            val formatString = intent.getStringExtra("format_string")
            String.format(formatString, "argument")
        }
    }
    ```

### Expected Behavior

When running Opengrep with the rule and code above, the taint analysis should find a path from the source (`getStringExtra`) to the sink (`String.format`) in **both** `processIntentData1` and `processIntentData2`. Two findings should be reported.

### Actual Behavior

Opengrep only reports a finding for `processIntentData2`. The taint flow in `processIntentData1` is missed due to the use of the Elvis operator, resulting in a false negative.

---

This appears to be a limitation in how the analysis engine models this specific Kotlin operator. If the team agrees this is a valid issue, I would be happy to prepare a Pull Request to address it.

Thank you for your work on this great tool.
