### ISSUE TITLE
Kotlin: Taint analysis fails to propagate through `.let` scope function

### ISSUE THREAD

**Issue by fxbru** [opengrep/opengrep#313]
### Description

Hello Opengrep Team,

I've encountered a case where taint analysis for Kotlin does not seem to track dataflow through the `.let` scope function. This results in false negatives for rules that rely on taint mode, as the engine loses the taint trail when a variable is passed into a `.let` block.

### Steps to Reproduce

1.  **Rule:** A minimal taint-tracking rule.
    ```yaml
    rules:
    - id: scope-function-taint-test
      mode: taint
      pattern-sources:
        - pattern: mySource(...)
      pattern-sinks:
        - pattern: mySink(...)
      message: Scope functions taint analysis test
      languages: [kotlin]
      severity: INFO
    ```

2.  **Kotlin Code:** A test file demonstrating the issue with both implicit `it` and explicitly named lambda variables.
    ```kotlin
    // test.kt
    fun mySource(): String = "tainted"
    fun mySink(data: String) { /* sink */ }

    // Case 1: Taint flow is NOT detected
    fun testTaintWithImplicitIt() {
        val taintedVar = mySource()
        taintedVar.let {
            mySink(it)
        }
    }

    // Case 2: Taint flow is NOT detected
    fun testTaintWithExplicitVar() {
        val taintedVar = mySource()
        taintedVar.let { v ->
            mySink(v)
        }
    }

    // Case 3: Taint flow IS detected (Control)
    fun testTaintWithDirectCall() {
        val taintedVar = mySource()
        mySink(taintedVar)
    }
    ```

### Expected Behavior

Opengrep should report **three** findings, identifying a taint flow from `mySource()` to `mySink()` in all three test functions.

### Actual Behavior

Opengrep only reports **one** finding, for `testTaintWithDirectCall`. The taint flow is not detected in the two cases that use the `.let` scope function.

---

This limitation seems to apply to other scope functions as well. If the team agrees this is a valid issue that needs addressing, I would be happy to contribute a Pull Request to help resolve it.

Thank you for your time and for this excellent tool.
