### ISSUE TITLE
For Swift, some source patterns are broken

### ISSUE THREAD

**Issue by willem-delbare** [opengrep/opengrep#6]
The following taint source is broken for Swift

```
    pattern-sources:
      - patterns:
          - pattern-either:
            - patterns:
              - pattern-either:
                - pattern-inside: |
                    func $FUNC(..., $INPUT: $TYPE,...) {
                      ...
                    }
              - pattern-either:
                  - pattern: $INPUT
```
