### ISSUE TITLE
Python pattern not working depending on line endings

### ISSUE THREAD

**Issue by willem-delbare** [opengrep/opengrep#90]
The following rule works with Linux style line endings, but breaks if you have windows style line endings

```
rules:
  - id: test
    message: test
    mode: taint
    languages:
      - python
    severity: ERROR
    pattern-sinks:
      - pattern-either:
          - patterns:
              - pattern: |
                  f"$ABC{$EXPR}..."
    pattern-sources:
      - patterns:
          - pattern: $SOURCE
          - pattern-inside: |
              def $FUNC(..., $SOURCE, ...):
                  ...

```
                 

```
def query(table2, table):

    columns_query_dest = f"semgrep '{table2}'\
        --config '{table}' "
```
