### ISSUE TITLE
Inconsistent miss of matches in C#

### ISSUE THREAD

**Issue by nir-valtman** [opengrep/opengrep#92]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.
1. Add the following rule:
```yaml
rules:
  - id: identified-parameter-in-csharp-code
    languages:
      - csharp
    severity: ERROR
    message: Detected the parameter name(s) `$PARAM` inside `$FUNC`
    patterns:
      - pattern-either:
          - patterns:
              - pattern: |-
                  enum $FUNC {
                    ...,
                    $PARAM,
                    ...
                  }
              - focus-metavariable: $PARAM
          - patterns:
              - pattern-either:
                  - pattern: $X $FUNC(..., $T $PARAM, ...) { ... }
                  - pattern: $T $FUNC = (..., $PARAM, ...) => ...;
              - metavariable-regex:
                  metavariable: $T
                  regex: (?i)^(?!(boolean|int|float|double))
              - focus-metavariable: $PARAM
          - patterns:
              - pattern-either:
                  - pattern: $T $PARAM;
                  - pattern: $T $PARAM = $VAL;
                  - pattern: $T $PARAM = new $U(...);
              - pattern-inside: |-
                  class $FUNC {
                    ...
                  }
              - pattern-not-inside: |-
                  $X $FUNC2(...) {
                      ...
                  }
              - metavariable-regex:
                  metavariable: $T
                  regex: (?i)^(?!(boolean|int|float|double))
              - focus-metavariable: $PARAM
          - patterns:
              - pattern-either:
                  - pattern: |-
                      $T $FUNC(...) 
                      { 
                        ... 
                        return $PARAM;
                        ...  
                      }
                  - pattern: |-
                      $T $FUNC(...) 
                      { 
                        ... 
                        return (..., $PARAM, ...);
                        ...  
                      }
                  - pattern: |-
                      $T $FUNC(...) 
                      { 
                        ... 
                        return new $TYPE(..., $PARAM, ...);
                        ...  
                      }
              - pattern-not-inside: |-
                  class $CLASS {
                    ...
                    $VAR $PARAM;
                    ...
                  }
              - pattern-not-inside: |-
                  class $CLASS {
                    ...
                    $VAR $PARAM = $VAL;
                    ...
                  }
              - focus-metavariable: $PARAM
      - metavariable-regex:
          metavariable: $PARAM
          regex: (?i)(alice|bob|eve)

```
2. Add the following file:
```cs
// ruleid: identified-parameter-in-csharp-code
public void PrintNames(string AliceSTR, int BobINT)
{
    Console.WriteLine($"Names: {AliceSTR} {str(BobINT)}");
}

// ruleid: identified-parameter-in-csharp-code
public void GreetStringName(string AliceSTR = "John", int BobINT = 12)
{
    Console.WriteLine($"Hello, {AliceSTR}");
}

public class User
{
    // ruleid: identified-parameter-in-csharp-code
    public string AliceUserName;
    // ok: an int, so not counting it
    public int AliceUserId;
}

public class Consumer
{
    // ruleid: identified-parameter-in-csharp-code
    public string BobConsumerName { get; set; } = "Bob";
    // ok: int value
    public int BobConsumerId { get; set; } = 10;
}

// ruleid: identified-parameter-in-csharp-code
public void GetFullName(out string BobFirstName, out int BobLastName)
{
    FirstName = "Alice";
    LastName = "Brown";
}

public class Employee
{
    // ruleid: identified-parameter-in-csharp-code
    public static string BobEmployee = "Default";
    // ok: int
    public static int BobEmbployeeId = 10;
}

// ruleid: identified-parameter-in-csharp-code
public void IsValid(string? BobName, int? BobId)
{
    if (FirstName != null && LastName != null)
    {
       return true;
    }
    return false;
}

```
3. Run the scan. 
4. You will see that matches are identified only in the following lines: 2, 8, 30, 45. It is missing the results in lines 16, 24, 39.
5. Change the file to include only the first 20 lines. Here is the new code:
```cs
// ruleid: identified-parameter-in-csharp-code
public void PrintNames(string AliceSTR, int BobINT)
{
    Console.WriteLine($"Names: {AliceSTR} {str(BobINT)}");
}

// ruleid: identified-parameter-in-csharp-code
public void GreetStringName(string AliceSTR = "John", int BobINT = 12)
{
    Console.WriteLine($"Hello, {AliceSTR}");
}

public class User
{
    // ruleid: identified-parameter-in-csharp-code
    public string AliceUserName;
    // ok: an int, so not counting it
    public int AliceUserId;
}
```
6. Now all resuls in the first 20 lines are detected properly. More specifically, rows 2 and 8 are detected before, and row 16 as well. 

**Expected behavior**
Results are expected in the rows above in this first `cs` file (2, 8, 30, 45), plus in lines 16, 24, 39 

**Screenshots**
Seems like the results are hidden behind a pro feature:
![Image](https://github.com/user-attachments/assets/7f484ca9-e97c-49ca-9c7d-cc6dbc4c4218)
