### ISSUE TITLE
Language support: C# version 13

### ISSUE THREAD

**Issue by nir-valtman** [opengrep/opengrep#93]
**Is your feature request related to a problem? Please describe.**
C# introduced multiple changes that are not yet supported, such as:
1. Enhanced params Collections
The params keyword now supports a broader range of collection types beyond arrays, including List<T>, Span<T>, ReadOnlySpan<T>, and any type implementing IEnumerable<T> with an Add method. This allows for more flexible method signatures.
For example:
```cs
using System;
using System.Collections.Generic;

public class Program
{
    public static void Main()
    {
        PrintNumbers(1, 2, 3, 4, 5);

        var numbersList = new List<int> { 6, 7, 8 };
        PrintNumbers(numbersList.ToArray());

        ReadOnlySpan<int> span = stackalloc int[] { 9, 10, 11 };
        PrintNumbers(span.ToArray());
    }

    public static void PrintNumbers(params int[] numbers)
    {
        Console.WriteLine("Numbers: " + string.Join(", ", numbers));
    }

    public static void LegacyFunc(string foo)
    {
         Console.WriteLine(numbers);
    }
}
```
The following rule detects only `LegacyFunc` and not `PrintNumbers`:
```yaml
rules:
  - id: enhanced-param-collection
    patterns: 
      - pattern: void $FUNC($PARAM) { ... }
      - focus-metavariable: $PARAM
    message: Detected
    languages:
      - csharp
    severity: ERROR
```

2. Method Group Natural Type Improvements
Enhancements in method group handling streamline overload resolution by pruning non-applicable candidates early in the compilation process, reducing errors related to method group usage.
For example:
```cs
using System;

public class Program
{
    public static void Main()
    {
        Action action = DisplayMessage;
        action();
    }

    public static void DisplayMessage()
    {
        Console.WriteLine("Hello, World!");
    }
}
```
The following rule detects a result but in thr `Main` function instead the `DisplayMessage` function:
```yaml
rules:
  - id: method-group-natural-type-improvements
    mode: taint
    pattern-sources:
      - pattern: Action $ACTION = $FUNC;
    pattern-sinks:
      - pattern: void $FUNC(...) { ... }
    focus-metavariable: $FUNC
    message: Detected
    languages:
      - csharp
    severity: ERROR

```

**Describe the solution you'd like**
Ability to parse C# version 13 code

**Describe alternatives you've considered**
Regex-based parsing is possible but not sustainable 

**Use case**
Scan code bases with C# version 13 patterns

**Comment by dimitris-m** [comment]
About 1: 

It's necessary to expand the rule to catch such parameters separately...
Opengrep (and Semgrep) match such varargs parameters separately so the rule should be: 

```yaml
rules:
  - id: enhanced-param-collection
    patterns:
      - pattern-either: 
        - pattern: void $FUNC($PARAM) { ... }
        - pattern: void $FUNC(params $T[] $PARAM) { ... }
    message: Detected
    languages:
      - csharp
    severity: ERROR
```

With this rule, we obtain:

```bash
┌─────────────────┐
│ 2 Code Findings │
└─────────────────┘

    example1.cs
   ❯❯❱ enhanced-param-collection
          Detected

           17┆ public static void PrintNumbers(params int[] numbers)
           18┆ {
           19┆     Console.WriteLine("Numbers: " + string.Join(", ", numbers));
           20┆ }
            ⋮┆----------------------------------------
           22┆ public static void LegacyFunc(string foo)
           23┆ {
           24┆      Console.WriteLine(numbers);
           25┆ }
```

About 2: 

I think it's a parser issue, I'll fix it.
