### ISSUE TITLE
opengrep_windows_x86.exe does not work

### ISSUE THREAD

**Issue by daparic** [opengrep/opengrep#98]
**Describe the bug**
Running a simple invocation which worked on a Linux box, threw a long line of error messages in Windows 11

**To Reproduce**
`opengrep_windows_x86.exe --config=rule.yaml .`

where `rule.yaml` looked like:
```
rules:
  - id: avoid-malloc
    patterns:
      - pattern: malloc(...)
    message: "Avoid using `malloc()`, it is unsafe for our special case"
    languages: [c, cpp]
    severity: ERROR
```

**Expected behavior**
I expect a findings message and not a very long line of error messages. 

**Screenshots**
Full console error logs: https://gist.github.com/daparic/772bf062ee89a9b2febf1945d5e54363

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Opengrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Environment**
I'm running an official binary from github release. I'm using Windows 11

**Use case**
Exploring on C/C++ static analysis
